spring:
  datasource:
    url: jdbc:postgresql://propostaDB:5432/estudo
    username: user
    password: user
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    proposta:
      concluida: proposta-concluida.ms-proposta

  propostapendente:
    exchange: proposta-pendente.ex
  propostaconcluida:
    exchange: proposta-concluida.ex
