spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estudo
    username: user
    password: user
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect